### ISSUE TITLE
Add support for the most widely used STM32F1xx series MCUs

### ISSUE THREAD

**Issue by wuwbobo2021** [David-OConnor/stm32-hal#105]
STM32F1 is probably the most popular series in ST’s product line for many years. Is there any plan about it?
There’s another crate `stm32f1xx-hal`, lacking some functions (especially those for drving TIMs), and its development progress seems slower than `stm32f4xx-hal`, why is this the case?

**Comment by David-OConnor** [comment]
No. Focusing on newer series.
