### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by ljalyn0820** [David-OConnor/stm32-hal#12]
..\stm32-hal2-0.2.8\src\timer.rs:319:13
319 |             pub fn countdown(&self) -> u32 {
    |             |
    |             duplicate definitions for `countdown`
    |             other definition for `countdown`
All pub fn void reported errors.

**Comment by David-OConnor** [comment]
Something feels off about this. GH bot?

**Comment by ljalyn0820** [comment]
hi, 
 In the  Cargo.toml, stm32-hal2 = { version = "^0.2.8", features = ["f4", "stm32f4"]},when i cargo build,
error：
..\stm32-hal2-0.2.8\src\timer.rs:319:13
319 | pub fn countdown(&self) -> u32 {
| |
| duplicate definitions for countdown
| other definition for countdown
All pub fn void reported errors.
error[E0592]:duplicate definitions with name `set_prescaler`

**Comment by David-OConnor** [comment]
Hi! This is a documentation issue. The available features for f4 are shown in Cargo.toml here: https://github.com/David-OConnor/stm32-hal/blob/main/Cargo.toml#L83

So, the line in Cargo.toml should be something like this:
`stm32-hal2 = { version = "^0.2.8", features = ["f405", "f4rt"]}`

There's a line that's supposed to throw a compile error in `lib.rs`, but it's not working properly. I'll update the Readme to provide guidance on this. Thanks for bringing it up - let me know if you still have issues after making this change.

**Comment by ljalyn0820** [comment]
Hi,I see. Thank you for your help！

**Comment by David-OConnor** [comment]
Readme updated to be more clear

**Comment by ljalyn0820** [comment]
OK,Thanks!
