### ISSUE TITLE
I2c support for f3x4

### ISSUE THREAD

**Issue by alianse777** [David-OConnor/stm32-hal#13]
I tried to remove feature gate for i2c module on f3x4 and with some minor changes in util.rs it seems to work out of the box.
Are there any hidden issues with it?
If no, I can open PR.

**Comment by David-OConnor** [comment]
Good call. That must have been a temporary workaround.

**Comment by David-OConnor** [comment]
It looks like the change may just to not allow I2C2 on F3x4. Ie feature gate `I2cDevice::Two` in its enum, and match arms, like we do for WB.

**Comment by David-OConnor** [comment]
[Fixed](https://github.com/David-OConnor/stm32-hal/commit/522fe7ca3bac6ddd663449df7ef5a3e9c1efccaa#diff-a0188da217f7d7a7717e82f613ce4e305655787f4b8900c577c47d711b4d27eaR80)
