### ISSUE TITLE
Support for STM32F2

### ISSUE THREAD

**Issue by reidrankin** [David-OConnor/stm32-hal#20]
So I'd love to use this in a project targeting the STM32F205RGT6. It's got a [PAC](https://docs.rs/stm32f2/0.13.0/stm32f2/) already, but I don't know how difficult would it be to add support for the F2 family. If it's something I can do myself I'd love to contribute!

**Comment by David-OConnor** [comment]
Hi. Unfortunately, F2 is too old for this project; out of scope. It's intended to be used for new projects, and the F2 family is only suitable for existing ones.
