### ISSUE TITLE
Family support

### ISSUE THREAD

**Issue by David-OConnor** [David-OConnor/stm32-hal#3]
Families supported:

- [x] f3
- [x] f4
- [x] l4
- [x] l5
- [ ] u5
- [x] g0
- [x] g4
- [x] h7

**Comment by theunkn0wn1** [comment]
Support for F4 would be appreciated.

**Comment by David-OConnor** [comment]
Done

**Comment by David-OConnor** [comment]
Closing this. All planned families implemented except for U5, which we don't have a PAC for yet.
