### ISSUE TITLE
rtc example reselect_input() on wrong struct?

### ISSUE THREAD

**Issue by AShriki** [David-OConnor/stm32-hal#32]
https://github.com/David-OConnor/stm32-hal/blob/63319645b0d54c898753c6846916796a1b6ed7d2/examples/rtc.rs#L76
Hello! Thanks for working on this wonderful crate. 
I noticed in the rtc example that reselect_input() is called on crate instead of a Clocks instance. it seems to me like you intended to call this method like so:
`clock_cfg.reselect_input();` 
Please correct me if I'm wrong. I'm very new to rust so I may be misunderstanding.

**Comment by David-OConnor** [comment]
You're correct - good catch. Fixed in latest commit.
