### ISSUE TITLE
More docs on design differences between crates from stm32-rs organization

### ISSUE THREAD

**Issue by myrfy001** [David-OConnor/stm32-hal#35]
I now know that this great project is different from crates at stm32-rs organization in some ways like:
* this is a all in one project while the crates from stm32-rs targets only a single series.
* it use conditional compile instead of using traits

but this is only what I thought about the difference, maybe not right.

I really hope that the author can provide more design philosophy of this project since I don't have enough effort to look through the crates from stm32-rs and this one to find the differences. With your help, we can decide whether to use stm32-hal2 or other hal impl from stm32-rs more easily.

thanks.

**Comment by David-OConnor** [comment]
Updated. What do you think?
