### ISSUE TITLE
TIM1/TIM8 CC channels broken on STM32L476 

### ISSUE THREAD

**Issue by badrbouslikhin** [David-OConnor/stm32-hal#43]
Hello,

- When using TIM1, there's a panic when trying to enable PWM output on channel 3 or 4.
- When using TIM8, there's a panic when trying to enable PWM output on anything but channel 1.

I believe this is related to [this line](https://github.com/David-OConnor/stm32-hal/blob/3e21c6c5e8dc9b60aeda7af34002302a6fca724f/src/timer.rs#L1578) and [this line](https://github.com/David-OConnor/stm32-hal/blob/3e21c6c5e8dc9b60aeda7af34002302a6fca724f/src/timer.rs#L1652).

Is it the intended behavior?

Thanks!

**Comment by David-OConnor** [comment]
I confirmed in the RM that L476 (as well as some other variants) have up to 6 channels on TIM1 and TIM8. The root of this is a [PAC bug](https://docs.rs/stm32l4/latest/stm32l4/stm32l4x5/tim1/index.html). Would need a YAML patch. Workaround in the mean while is probably to write to the relevant registers directly using an integer you calculate. Long term is getting the PAC fixed.

**Comment by David-OConnor** [comment]
Of note, now that you brought this to my attention, I pushed a change allowing up to 4 channels on TIM8 on most STM32s. L4 and L5 excepted; they have more channels, but the PAC is missing them. PAC is bugged on TIM1 for many variants.

**Comment by David-OConnor** [comment]
Good call; tested; will be in the next commit. The PAC issue is having to feature-gate `cc4np`. That's easy to work around in the PAC though. Nice find/fixes!

**Comment by David-OConnor** [comment]
Released
