### ISSUE TITLE
f303 stuck at pplstart

### ISSUE THREAD

**Issue by MauroMombelli** [David-OConnor/stm32-hal#48]
tested with both external and default config, it get stuck at 
while rcc.cr.read().pllrdy().is_ready() {}, line 488 of f.rs

**Comment by David-OConnor** [comment]
Sounds like a bug! Does it work if you configure the clock source to be HSI or HSE? (Without PLL)

**Comment by MauroMombelli** [comment]
I just tried to replicate from the quickstart project, as playing around with linker flags and similar i managed to make it work, but somehow #[defmt::panic_handler] wont work anymore and i need to use a standard #[panic_handler]

Clean quickstart will hardfault on startup

only changes are: stm32-hal2 = { version = "^1.4.5", features = ["f303", "f3rt"]}
and
runner = "probe-run --chip STM32F303VCTx" # to list chips, run `probe-run --list-chips.`
(flash and ram should be ok)

from probe-rs:
(HOST) INFO  flashing program (17 pages / 17.00 KiB)
(HOST) INFO  success!
Error: An error with the usage of the probe occured

from openocd
![image](https://user-images.githubusercontent.com/6372561/178140010-d330fe9f-c0f8-4cc8-bcc4-f7b11f9c9f94.png)

interestingly the main() is never hit, and all exception frame seems 0; the old project now work tho. not really sure what is going on here.

**Comment by David-OConnor** [comment]
Have you adjusted `memory.x`?

**Comment by MauroMombelli** [comment]
yes, just double checked both flash and ram, also verified with the working project

**Comment by David-OConnor** [comment]
Are you using a current version of probe-run ?

**Comment by MauroMombelli** [comment]
yes, using both probe-run latest version (installed yesterday) and release mode, simply run with `cargo run`.
Also tested with openocd + gdb (setup work with the other project, so i am pretty confident)

**Comment by David-OConnor** [comment]
What's the word?

**Comment by lestofante** [comment]
what is the meaning of "What's the word?"?

**Comment by David-OConnor** [comment]
Status

**Comment by David-OConnor** [comment]
Closing due to lack of input.

**Comment by MauroMombelli** [comment]
tested against current version, 1.5.3, the issue seems to be fixed

**Comment by David-OConnor** [comment]
Thanks!
