### ISSUE TITLE
Implement RccPeriph and BaudPeriph for UART4, 5 traits 

### ISSUE THREAD

**Issue by AShriki** [David-OConnor/stm32-hal#50]
Hi, I'm using the stm32l476re and it seems that these two traits are semi implemented for UART 4 and 5 in util.rs, but are commented out or incomplete. Can we open these up to the L4 family (minus l4x3, l4x2, l4x1) as well? Checking against the SVD, the entire family has UART 4 and 5. I'd be glad to submit a pull request if you are looking for contributors.

**Comment by David-OConnor** [comment]
Done
