### ISSUE TITLE
Feature gate more of the timer peripherals

### ISSUE THREAD

**Issue by theunkn0wn1** [David-OConnor/stm32-hal#6]
I decided to look into introducing F4 support.

the F4 does not have `TIM15`,`TIM16`. FEature gating will be necessary for `src.timer.rs`'s include on line 9.

The DAC has a different name, but feature gating exists here so that can be addressed directly.

**Comment by David-OConnor** [comment]
Re timers: Across families, the functionality (including what a timer of a given name can do) is similar or identical. But, each variant has its own combination of timers it uses, so that module is loaded with feature-gating on the imports and macro-calls.

**Comment by theunkn0wn1** [comment]
Yep, the issue is `TIM15` and `TIM16` specifically are not feature gated, and don't exist on the F446 (and likely others in the F4 family; would need to acquire additional reference manuals).

**Comment by David-OConnor** [comment]
Oh weird! For a while I thought TIM1 was universal too.
