### ISSUE TITLE
probe-run timeout error

### ISSUE THREAD

**Issue by kacper-cholewinski** [David-OConnor/stm32-hal#63]
Hi,
I try to flash quickstart code onto my NUCLEO - STM32F303K8T6, but it goes like this:
```
(HOST) INFO  flashing program (18 pages / 18.00 KiB)
(HOST) INFO  success!
Error: An error with the usage of the probe occurred

Caused by:
    Operation timed out
error: process didn't exit successfully: `probe-run --chip STM32F303K8Tx target\thumbv7em-none-eabihf\release\project_name` (exit code: 1)
```

I've updated .cargo/config.toml and memory.x, and generally did all things according to instructions.

Solutions will be appreciated :)

**Comment by David-OConnor** [comment]
Are you able to connect using Stm32CubeProgrammer?

**Comment by kacper-cholewinski** [comment]
Hi, thanks for quick answer.

Yes, I can connect and flash program using Cube without problems.

Moreover, I've tried to flash old embassy-rs project to same board, using probe-run and it didn't work either. Few months ago I did it without any problems.

**Comment by David-OConnor** [comment]
Weird! No idea. Is `probe-run` up to date? ie `cargo update prob-run --force`.

**Comment by kacper-cholewinski** [comment]
Unfortunately, it is. Is there a way to check what is exactly wrong with the flash? Or maybe I need to post issue at probe-run repo?

**Comment by kacper-cholewinski** [comment]
Ok, so I used verbose flag on probe-run and I got this:
`couldn't find valid stack range, not placing stack canary`
What does it mean?

**Comment by kacper-cholewinski** [comment]
Ok, but now I've updated hal to latest version and flashing works fine.

I assume that something changed in this release, or maybe rust compiler just hates me. :)

**Comment by kacper-cholewinski** [comment]
I've tested some more and my conclusion is - I made mistake in memory.x file at first and corrected it later, but there is need for cargo clean for changes in memory.x to take effect.

I hope at least it will help someone else.
