### ISSUE TITLE
Pinouts for stm32l476-nucleo and stm32l476-eval boards should be different.

### ISSUE THREAD

**Issue by seanybaggins** [David-OConnor/stm32-hal#75]
For the stm32l476-eval, Pin groups G and H exist. This is not reflected in the current hal.

**Comment by David-OConnor** [comment]
Fixed. (Also applies to L4x5)

**Comment by seanybaggins** [comment]
Just want to clarify. stm32l476-**nucleo**'s don't have these pins exposed on the board. Currently, it is the responsibility of the user not to configure a gpio pin that is not exposed for that board.

**Comment by David-OConnor** [comment]
This crate doesn't distinguish between dev boards - both of those use similiar MCUs, and that MCU sub-family (L4x6) supports ports G and H. I added them to L4x5 and L4x6 in response to this issue.

**Comment by seanybaggins** [comment]
Awesome turnaround. Thank you for being so responsive!
