### ISSUE TITLE
Question: SPI always reading 255

### ISSUE THREAD

**Issue by Simonrazer** [David-OConnor/stm32-hal#76]
Heyo, I have another question. I have a STM32F407G-DISC1. I want to use the accelerometer on it with SPI.
I read a bunch of threads/the datasheets of the board, but when I try to use it if this HAL all I read over SPI is 255, no matter what register.
Based on this table im pretty sure I am using the right pins.
![grafik](https://user-images.githubusercontent.com/30187223/220338523-e07ce829-cc14-42dd-9f55-1f0d8e47951a.png)
![grafik](https://user-images.githubusercontent.com/30187223/220338653-fab44561-7b44-44d3-b323-fc9cbaf9ff29.png)

Here is (the interesting part of) my code:   
       
        //Pins
        let mut sck = Pin::new(Port::A, 5, PinMode::Alt(5));
        let mut miso = Pin::new(Port::A, 6, PinMode::Alt(5));
        let mut mosi = Pin::new(Port::A, 7, PinMode::Alt(5));
        let mut cs = Pin::new(Port::E, 3, PinMode::Output); 

        //Set SPI mode 0, rest default
        let spi_cfg = SpiConfig{mode: SpiMode::mode0(), ..Default::default()};
        let mut spi = Spi::new(dp.SPI1, spi_cfg, BaudRate::Div32); //Mode and Baud Rate are correct, working C++ code uses the same

        cs.set_low(); //Chip Select for SPI/the Accelerometer is active low
        let write_buf1 = [0x20, 0b01000111];//The Acc. is of by default, enable it by writing those regss
        spi.write(&write_buf1).ok();
        cs.set_high();

        cs.set_low();
        let mut rb:[u8;1] = [0x20]; //The register is r/w so lets see if that write did anything
        spi.transfer(&mut rb).ok();
        println!("{:b}", rb); //prints: 11111111
        //No matter where I read, i get 255..

I know this isnt really a place to ask this stuff, but I am at a total loss. Any help is greatly appreciated!!

**Comment by David-OConnor** [comment]
What happens if you set CS high after the transfer, and before printing the buf?

**Comment by Simonrazer** [comment]
No change, 255 all the way

**Comment by David-OConnor** [comment]
Are you able to read the device id? (SHould be a register for that).

**Comment by Simonrazer** [comment]
Ah okay, that makes sense.
Unfortunatly it didnt help. Still having 255 in all places of the reading buffer when printing.
Yes the ID register (WHO_AM_I i guess) is also 255, even tho it shouldn't be

**Comment by David-OConnor** [comment]
What accel/IMU is it?

Of note, AFAIK other than the things I mentioned, your code looks right. (Setting CS high after an operation is required on some SPI devices, but not others). Of note, I'm using an SPI Acc/Gyro on one of my projects, although that's on H7 and G4. It could be a bug in this lib's F4 SPI implementation - I haven't tested that.

**Comment by David-OConnor** [comment]
From that it sounds like the clocks are fine.

**Comment by Simonrazer** [comment]
Unforunatly I fail to get the other HAL to work enough. I cant get rprintl to work, or actually anything else than blinking LEDs 😅(Really appreciate the much better docs+examples here! ^^)

Another thing, the F407 has 3 SPI devices. When using the second one all communication of USB just fails until I erase the flash. The third one only prints 0 so far, but as it doesnt share pins with the Motion sensor I think that may even make sense for once. Going to find cables to connect them today

**Comment by David-OConnor** [comment]
Any updates on this?

**Comment by Simonrazer** [comment]
Sorry, not really. I switched to I2C and an external IMU, that worked. Code is here: https://github.com/Simonrazer/Embedded-Rust-Demo/blob/main/src/main.rs
