### ISSUE TITLE
Can you provide a DMA example for boards that need to use dma::cfg_channel?

### ISSUE THREAD

**Issue by seanybaggins** [David-OConnor/stm32-hal#82]
Hi David,

Could you provide an example of how to use DMA when your only option is to use `dma::cfg_channel`? My board, the `stm32l476`, does not have access to the `dma::mux` function.

Any help would be deeply appreciated.

**Comment by David-OConnor** [comment]
You need to take no action, other than ensuring you're using the right channel. cfg_channel is internal
