### ISSUE TITLE
Crates.io links from nrf-hal to this

### ISSUE THREAD

**Issue by ivario123** [David-OConnor/stm32-hal#89]
# Issue

It seems that you own the nrf-hal crate on [crates.io](https://crates.io/crates/nrf-hal) but that crate links to this repo, which is not the [nrf-hal](https://github.com/nrf-rs/nrf-hal). This makes it rather confusing to find the actual nrf-hal.

## Suggested fix

The easiest way would to [yank](https://doc.rust-lang.org/cargo/commands/cargo-yank.html) this crate from crates.io to make it clear that this is not the nrf-hal, moreover it could be worth updating the description of the project to link to the [nrf-hal](https://github.com/nrf-rs/nrf-hal) thus minimizing confusion.

**Comment by David-OConnor** [comment]
Link fixed
