### ISSUE TITLE
STM32G4 missing GPIO port 'G'

### ISSUE THREAD

**Issue by systec-ms** [David-OConnor/stm32-hal#90]
First of all, thanks for the HAL ;).

I am creating this issue since I miss the ability to use the pin `PG10-NRST` on my `SMT32G491`.

Since the Port::G is disabled by the `G4` feature.

Depending on how I find the time, I'll take a closer look and try to fix it myself.

**Comment by David-OConnor** [comment]
Nvm; added/on the GH repo.
