### ISSUE TITLE
embedded_hal::serial::{Read, Write} are implement blocking (while should be nb)

### ISSUE THREAD

**Issue by systec-ms** [David-OConnor/stm32-hal#91]
Good day,

i have taken a look into the `embedded-hal` UART implementation and found that it does not behave as expected.
My expedition would be an instance return of `WouldBlock` from the `write`/`read` call if  `txe`/`rxne` is not set. At the moment there is an endless wait.
Now i am curious and ask myself if there is any reason for that?

**Comment by David-OConnor** [comment]
Closing as switched to EH 1.0.
